global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # TrackOps Server (running locally)
  - job_name: 'trackops-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
