version: '3.8'

services:
  # Grafana Dashboards
  grafana:
    image: grafana/grafana:10.0.0
    container_name: trackops-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  grafana_data:
